### ISSUE TITLE
Record Audio UI position

### ISSUE THREAD

**Issue by MateuszLas421** [ArturWyszomirski/Plugin.Maui.Chat#30]
What should the behavior of the button be when the editor expands or when the button to play the recording appears? What position should it have?

Currently screnshots:  
- Android
![Screenshot_20240927_140002 1](https://github.com/user-attachments/assets/6d8d739a-5c56-4cf8-80c8-844223846774)
![Screenshot_20240927_140017 1](https://github.com/user-attachments/assets/a08b636a-eb87-481c-8f13-3d3837abbc9e)
![Screenshot_20240927_140147 1](https://github.com/user-attachments/assets/995b1671-977f-4795-94a7-561db3f3b8e1)

- iOS
![IMG_0701](https://github.com/user-attachments/assets/0df2d55c-dcb6-460f-812b-beb572f63b91)
![IMG_0702](https://github.com/user-attachments/assets/4909a8f6-dc36-411f-901d-596d96e9adfd)
![IMG_0703](https://github.com/user-attachments/assets/e1f175b7-864d-451b-8f2b-d39e3ba19bd4)

**Comment by ArturWyszomirski** [comment]
The buttons should be bottom aligned (and once was :P). Good job with pointing that out!
